//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public int Код_клиента { get; set; }
        public int Код_состояния_номера { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Пол { get; set; }
        public string Паспортные_данные { get; set; }
        public Nullable<int> Телефон { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual Состояние_номера Состояние_номера { get; set; }
    }
}
