//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номера()
        {
            this.Бронь = new HashSet<Бронь>();
            this.Состояние_номера = new HashSet<Состояние_номера>();
        }
    
        public int Код_номера { get; set; }
        public int Код_тип_номера { get; set; }
        public int Код_доп__удобства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь { get; set; }
        public virtual Доп__Удобства Доп__Удобства { get; set; }
        public virtual Тип_номера Тип_номера { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состояние_номера> Состояние_номера { get; set; }
    }
}
