//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состояние_номера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Состояние_номера()
        {
            this.Бронь = new HashSet<Бронь>();
            this.Клиент = new HashSet<Клиент>();
        }
    
        public int Код_состояние_номера { get; set; }
        public int Код_номера { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_брони { get; set; }
        public Nullable<System.DateTime> Дата_заезд { get; set; }
        public Nullable<System.DateTime> Дата_выезд { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<bool> isFree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиент> Клиент { get; set; }
        public virtual Номера Номера { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
